language: c
sudo: required
dist: trusty

git:
  depth: 3

os:
  - osx
  - linux

env:
  global:
    - VERBOSE=1
  matrix: # We don't install x11 32-bit libraries, so skip shared libraries on -m32
    - ARCH=i386 SHARED=OFF
    - ARCH=amd64 SHARED=ON

matrix:
  exclude: # This is already covered by building universal (fat) libraries by default
  - os: osx
    env: ARCH=i386 SHARED=OFF

before_script:
  - export CFLAGS="-std=gnu99"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get install -y gcc-multilib
                              libopenal-dev
                              libxcursor-dev libxinerama-dev
                              mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev
                              libgl1-mesa-dev libglu1-mesa-dev libglew-dev;
      export RAYLIB_PACKAGE_SUFFIX="-Linux-$ARCH";
      if [ "$ARCH" == "i386" ]; then export CFLAGS="$CFLAGS -m32"; fi;
      if [ "$ARCH" == "amd64" ]; then export CFLAGS="$CFLAGS -m64"; fi;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export RAYLIB_PACKAGE_SUFFIX="-macOS"; fi
  - "$CC --version"

script:
  - mkdir build
  - cd build
  - cmake -DMACOS_FATLIB=ON -DSTATIC_RAYLIB=ON -DSHARED_RAYLIB=$SHARED -DBUILD_EXAMPLES=OFF -DBUILD_GAMES=OFF ..
  - make
  - make package

deploy:
  provider: releases
  api_key:
    secure: LvqUIAN/3dJul+Ra2iK3tSaNG5IwsNMmGIwVMy0DK5IBCxiQPBc9pWGiE30RTBPt6Z+N4BhMEE8DtUl+vnISlMoHWNIIhF2zwC66hs/F7zY7qEITMRSmfiLcqxQysknFOnJB06CATgXcFqlEo9j+t4abrG/f3qcb92J4O2uNz336Au2myTx93Q5MxbyA7KiUuEutFnb2dWiPCY4d+sGeXEfsiD2R7aj/8MaWOkoGdZVrTkI9juMgvpImkjQBArvqdjUMeT3MsRrwgOIq5v2GFV9dOl8k1WzPeT8B2JHh00ed/o1/wuFq/cLLOxtYo2+Pv3+xatOrlexoX0WkDm7C9/L1W5U4rLexU3CQ9mMBmHPnp6k/WXZ5QXEE4uUF0+LpN3XlIXzFpdZmZiVV8VLxg2WvyncMmivYiu7/MTkyfZxyKkzwl7sZZslzHA9kOGedGaN7b7/2B77OFHoQK8lKfdFml7jJnarh+89nenNZYMab0E8qkOJOyb2bYlDTa0/2nyxGiyymYgq6YHLNrDbhqB/1LzdgzjMliQ8ri5q9Ux2vjfcqOzhfAmcwFwnY/D6yXJWYi0DWpHZdpKl3du6dYDrypW91/yDWbwiJ/YhrE7ZunzrcB6GH/QkbuzWxdCth39rQAHih8DG01co/K3Gvi4yGjvIH5tFUpyEolMnpMiA=
  file_glob: true
  file: raylib-*.tar.gz
  skip_cleanup: true
  on:
    repo: raysan5/raylib
    branch: develop
