#os: Visual Studio 2015

clone_depth: 5

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

init:
  - cmake -E remove c:\programdata\chocolatey\bin\cpack.exe
  - set PATH=%PATH:C:\Program Files (x86)\Git\usr\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if [%BITS%]==[32] set MINGW=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32
  - if [%BITS%]==[64] set MINGW=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64
  - if [%COMPILER%]==[mingw] set PATH=%MINGW%\bin;%PATH%
  - set RAYLIB_PACKAGE_SUFFIX=-Win%BITS%-%COMPILER%
  - set VERBOSE=1

environment:
  matrix:
    - compiler: mingw
      bits: 32
      examples: ON
    - compiler: mingw
      bits: 64
      examples: ON
    - compiler: msvc15
      bits: 32
      examples: OFF
    - compiler: msvc15
      bits: 64
      examples: OFF

before_build:
  - if [%compiler%]==[mingw] set CFLAGS=-m%BITS% & set LDFLAGS=-m%BITS% & set GENERATOR="MinGW Makefiles"
  - if [%COMPILER%]==[msvc15] if [%BITS%]==[32] set GENERATOR="Visual Studio 14 2015"
  - if [%COMPILER%]==[msvc15] if [%BITS%]==[64] set GENERATOR="Visual Studio 14 2015 Win64"
  - mkdir build
  - cd build

build_script:
  - cmake -G %GENERATOR% -DSTATIC=ON -DSHARED=ON -DBUILD_EXAMPLES=%examples% -DBUILD_GAMES=%examples% -DINCLUDE_EVERYTHING=ON ..
  - cmake --build . --target install

after_build:
  - cmake --build . --target package

before_test:

test_script:

artifacts:
  - path: 'build\*.zip'

deploy:
  - provider: GitHub
    auth_token:
      secure: OxKnnT3tlkPl9365cOO84rDWU4UkHIYJc0D3r3Tv7rB3HaR2BBhlhCnl7g3nuOJy
    artifact: /.*\.zip/
    draft: false
    prerelease: false
    force_update: true
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only
