branches:
    only:
        - ci
        - master
skip_tags: true
environment:
    CFLAGS: /WX
    matrix:
        - BUILD_SHARED_LIBS: ON
        - BUILD_SHARED_LIBS: OFF
matrix:
    fast_finish: true
build_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% ..
    - cmake --build .
notifications:
    - provider: Email
      to:
        - ci@glfw.org
      on_build_failure: true
      on_build_success: false
